### NumPy Tutorial

NumPy is an amazing scientific computing library that is used by numerous other Python Data Science libraries. 
- mathematical, array and string functions 
- basic math functions 
- yand Linear Algebra, Statistics, Simulation, etc.


NumPy utilizes vector (1D Arrays) and matrice arrays (2D Arrays). 

### NumPy Arrays : Creating Arrays

In [1]:
import numpy as np
# Provides beautiful plots of numerous type that are either
# static, animated and/or interactive
import matplotlib.pylab as plt
from numpy import random

# A Python list
list_1 = [1, 2, 3, 4, 5]

# Create NumPy 1 dimensional (a axis) array list object of type byte (-128 to 127)
# A N-dimensional array is a usyally fixed size multidimensional
# array that contains items of the same type. 
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [2]:
np_arr_1.shape

(5,)

In [3]:
# Create multidimenional list
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create NumPy multidimensional (2 axis) array without defining type
np_m_arr_1 = np.array(m_list_1)

print(np_m_arr_1.shape)

np_m_arr_1

(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# You can also create arrays by defining the start value,
# stop value (up to but not include stop) and step amount
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# With floats define start, end and number of values
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [6]:
# You can create a 3 item array of zeroes
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
# You can create multidimensional arrays of zeroes by passing
# a tuple with the 1st value being rows and the 2nd columns
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Create array of 1s
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Get number of items in the array
np_m_arr_1.size

9

In [10]:
# Create array with defined values
np_arr_2 = np.array([1, 2, 3, 4, 5, 6])

In [11]:
# Get type for array
np_arr_2.dtype

# Data Types
# Boolean : np.bool_
# Char : np.byte
# Short : np.short
# Integer : np.short
# Long : np.int_
# Float : np.single & np.float32
# Double : np.double & np.float64
# np.int8 : -128 to 127
# np.int16 : -32768 to 32767
# np.int32 : -2147483648 to 2147483647
# np.int64 : -9223372036854775808 to 9223372036854775807

# Create random 5 value 1D array from 10 to 50
np.random.randint(10, 50, 5)

array([41, 28, 20, 34, 15])

In [12]:
# Create random matrix 2x3 with values between 10 and 50


In [13]:
np.random.randint(10, 50, size=(5, 2))

array([[12, 13],
       [18, 17],
       [14, 49],
       [31, 13],
       [35, 28]])

In [14]:
a = np.random.randint(1, 13, size=(4, 13))

In [15]:
a

array([[ 4,  4, 11,  4,  7,  5,  8,  1,  7, 11,  5,  4,  6],
       [ 8, 12,  5,  7,  5,  4,  5,  5, 12, 12, 12,  4,  8],
       [ 4,  4,  2,  3, 10, 10, 10,  7,  5,  1,  3,  1,  9],
       [ 2,  9,  1,  6, 12,  9, 10,  1,  9,  3, 12,  4,  1]])

In [16]:
a.size

52

In [17]:
np.random.sample(52)

array([0.02045632, 0.65233908, 0.45012423, 0.44483334, 0.33352612,
       0.0234488 , 0.93796352, 0.76877213, 0.14367266, 0.24651253,
       0.41751702, 0.46691496, 0.15438775, 0.95440738, 0.59949622,
       0.44324012, 0.89112945, 0.16504043, 0.91668332, 0.98274566,
       0.20905134, 0.58954781, 0.91945324, 0.35179339, 0.98569814,
       0.71926692, 0.10096813, 0.34925815, 0.5141837 , 0.38317157,
       0.18819233, 0.1691808 , 0.85540471, 0.00933805, 0.6035264 ,
       0.13438883, 0.17643173, 0.98652201, 0.76193536, 0.39209073,
       0.30216094, 0.3014088 , 0.33198013, 0.78340805, 0.18539672,
       0.3769264 , 0.35760394, 0.86945627, 0.40843438, 0.9295217 ,
       0.28841312, 0.21095812])

# deck of cards 2 shuffles - find the ace

In [18]:
b= np.arange(1, 53)

In [19]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52])

In [20]:
b.size

52

In [21]:
np.random.shuffle(b)

In [22]:
b

array([14, 25, 47, 19, 16, 44, 52, 13,  5, 41, 36, 43,  4, 11, 50, 35, 45,
       31, 15, 38, 27, 51, 34,  8, 30, 32, 26, 21,  9, 39, 23, 49, 12,  1,
       10,  2, 28, 24, 40, 20,  7, 17,  6,  3, 22, 48, 18, 42, 29, 46, 37,
       33])

In [23]:
np.random.shuffle(b)

In [24]:
b

array([14, 16,  7, 48, 50, 45, 23, 26,  8, 32, 17,  2, 20, 41, 38, 33, 11,
       10, 37, 52, 35, 18,  6, 21, 42, 44,  5, 34,  3, 13, 49, 27,  1, 28,
       39, 12, 22, 46, 24, 43, 19, 36, 29, 31, 47, 15, 30,  4, 51, 40,  9,
       25])

# if 1 represents the ace - how many days in chase the ace

In [25]:
np.where(b==1)

(array([32]),)

In [26]:
print(b[16])

11


In [27]:
b[17]

10

# chase the ace

In [28]:
for i in range(11):
    np.random.shuffle(b)
    print(np.where(b==1))

(array([4]),)
(array([44]),)
(array([19]),)
(array([40]),)
(array([3]),)
(array([43]),)
(array([34]),)
(array([13]),)
(array([37]),)
(array([4]),)
(array([41]),)


In [29]:
# Get help with a function
np.random.randint?

### Slicing and Indexes

In [30]:
# Change value at index
np_m_arr_1[0,0] = 2
np_m_arr_1.itemset((0,1), 1)
np_m_arr_1

array([[2, 1, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# Get size of array
np_m_arr_1.shape

(3, 3)

In [32]:
np_m_arr_1[0,0]

2

In [33]:
# Get value by index
np_m_arr_1[0,1]

1

In [34]:
np_m_arr_1.item(0,1)

1

In [35]:
# Get specific indices
np.take(np_m_arr_1, [0, 3, 6])

array([2, 4, 7])

In [36]:
# Replace provided index values with new values
np.put(np_m_arr_1, [0, 3, 6], [10, 10, 10])
print(np_m_arr_1)

[[10  1  3]
 [10  5  6]
 [10  8  9]]


In [37]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [38]:
# Start at 1st through 5th with 2 step
np_arr_1[:5:2]

array([1, 3, 5], dtype=int8)

In [39]:
np_arr_1[0:5:2]

array([1, 3, 5], dtype=int8)

# start:stop:step - 0 is the first item

In [40]:
# only get 2 items when we start at index==1 , the second element in a 5 element array
np_arr_1[1:5:2]

array([2, 4], dtype=int8)

In [41]:
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [42]:
# Get 2nd value from each row
np_m_arr_1[:,1]

array([1, 5, 8])

In [43]:
# Flip Array
np_arr_1[::-1]

array([5, 4, 3, 2, 1], dtype=int8)

In [44]:
# Get evens
evens = np_m_arr_1[np_m_arr_1%2==0]
evens

array([10, 10,  6, 10,  8])

In [45]:
# Get values > 5
np_m_arr_1[np_m_arr_1 > 5]

array([10, 10,  6, 10,  8,  9])

In [46]:
# 5 < value < 9
np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1 < 9)]

array([6, 8])

In [47]:
# 5 < value or value = 10
np_m_arr_1[(np_m_arr_1 > 5) | (np_m_arr_1 == 10)]

array([10, 10,  6, 10,  8,  9])

In [48]:
# Find uniques
np.unique(np_m_arr_1)

array([ 1,  3,  5,  6,  8,  9, 10])

### Reshaping Arrays

In [49]:
# Reshape array to 1 by 9
a_new = np_m_arr_1.reshape((1, 9))
np_m_arr_1

array([[10,  1,  3],
       [10,  5,  6],
       [10,  8,  9]])

In [50]:
a_new

array([[10,  1,  3, 10,  5,  6, 10,  8,  9]])

In [51]:
# notice the one above is still two dimensional
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
b_new = a_new[0]

In [53]:
# one d now
b_new

array([10,  1,  3, 10,  5,  6, 10,  8,  9])

In [55]:
# Reshape array to 2 by 5 (Items are either lost or 0s added)
# np_m_arr_1.resize((2,5))
# np_m_arr_1

In [56]:
# Transpose axes
np_m_arr_1.transpose()

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [57]:
# Swap axes 
np_m_arr_1.swapaxes(0,1)

array([[10, 10, 10],
       [ 1,  5,  8],
       [ 3,  6,  9]])

In [58]:
# Flatten in order
np_m_arr_1.flatten()

array([10,  1,  3, 10,  5,  6, 10,  8,  9])

In [59]:
# Flatten in column order
bb=np_m_arr_1.flatten('F')
bb

array([10, 10, 10,  1,  5,  8,  3,  6,  9])

In [60]:
np_m_arr_1 =np.arange(1,10).reshape(3, 3)
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np_m_arr_1[2,1]=2

In [62]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 2, 9]])

In [63]:
# Sort rows
np_m_arr_1.sort(axis=1)
print(np_m_arr_1)
# Sort columns

[[1 2 3]
 [4 5 6]
 [2 7 9]]


In [64]:
np_m_arr_1.sort(axis=0)
np_m_arr_1

array([[1, 2, 3],
       [2, 5, 6],
       [4, 7, 9]])

### Stacking & Splitting

In [65]:
# Generate random arrays
ss_arr_1 = np.random.randint(10, size=(2, 2))
print("ss_arr_1\n", ss_arr_1)

ss_arr_1
 [[6 1]
 [4 7]]


In [66]:
ss_arr_2 = np.random.randint(10, size=(2, 2))
print("ss_arr_2\n", ss_arr_2)

ss_arr_2
 [[1 9]
 [2 7]]


In [67]:
# Stack arr_2 under arr_1
np.vstack((ss_arr_1, ss_arr_2))

array([[6, 1],
       [4, 7],
       [1, 9],
       [2, 7]])

In [68]:
# Stack horizontally
np.hstack((ss_arr_1, ss_arr_2))

array([[6, 1, 1, 9],
       [4, 7, 2, 7]])

In [69]:
# Delete 2nd row on each array
ss_arr_3 = np.delete(ss_arr_1, 1, 0)
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print("ss_arr_3\n", ss_arr_3)
print("ss_arr_4\n", ss_arr_4)

ss_arr_3
 [[6 1]]
ss_arr_4
 [[1 9]]


In [70]:
# Combine arrays
np.column_stack((ss_arr_3, ss_arr_4))

array([[6, 1, 1, 9]])

In [71]:
# Stack in a 2D array
np.row_stack((ss_arr_3, ss_arr_4))

array([[6, 1],
       [1, 9]])

In [72]:
# Generate 4x13 array
ss_arr_5 = np.random.randint(13, size=(4, 13))
print("ss_arr_5\n", ss_arr_5, 'size', ss_arr_5.size)

ss_arr_5
 [[10  6  6  5 10  6  7  7  1  8  6  4  3]
 [12  4 10  1  7  8  6  1  8  6  9 12  1]
 [ 2  6  0  9  9  0  6 12 10  4 12  2  0]
 [ 5  8  7 10  1  2  2  2  0  8  1  7  6]] size 52


In [73]:
# Generate 2x10 array
ss_arr_5 = np.random.randint(10, size=(2, 10))
print("ss_arr_5\n", ss_arr_5)

ss_arr_5
 [[1 9 1 5 3 7 4 1 3 4]
 [4 5 6 2 8 7 4 9 6 2]]


In [74]:
# Split into 5 arrays taking from both arrays in multidimensional array
np.hsplit(ss_arr_5, 5)

[array([[1, 9],
        [4, 5]]),
 array([[1, 5],
        [6, 2]]),
 array([[3, 7],
        [8, 7]]),
 array([[4, 1],
        [4, 9]]),
 array([[3, 4],
        [6, 2]])]

In [75]:
# Split after 2nd & 4th column
np.hsplit(ss_arr_5, (2, 4))

[array([[1, 9],
        [4, 5]]),
 array([[1, 5],
        [6, 2]]),
 array([[3, 7, 4, 1, 3, 4],
        [8, 7, 4, 9, 6, 2]])]

### Copying

In [76]:
cp_arr_1 = np.random.randint(10, size=(2, 2))
# Both variables point at the same array
cp_arr_2 = cp_arr_1
print(cp_arr_2[0,0])
print(cp_arr_1[0,0])

# Change value
cp_arr_1[0,0] = 2
print("cp_arr_1\n", cp_arr_1)
print("cp_arr_2\n", cp_arr_2)

print(cp_arr_2[0,0])
print(cp_arr_1[0,0])

6
6
cp_arr_1
 [[2 6]
 [2 0]]
cp_arr_2
 [[2 6]
 [2 0]]
2
2


In [77]:
# Create a view of data where changes don't effect original
cp_arr_3 = cp_arr_1.view()
print("cp_arr_3\n", cp_arr_3)
cp_arr_3 = cp_arr_3.flatten('F')
print("cp_arr_3\n", cp_arr_3)
print("cp_arr_1\n", cp_arr_1)
# Copy and create new array
cp_arr_4 = cp_arr_1.copy()

cp_arr_3
 [[2 6]
 [2 0]]
cp_arr_3
 [2 2 6 0]
cp_arr_1
 [[2 6]
 [2 0]]


### Basic Math

In [78]:
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
# Add values
arr_3 + arr_4

array([ 3,  6,  9, 12])

In [79]:
# Subtract
arr_3 - arr_4

array([-1, -2, -3, -4])

In [80]:
# Multiply
arr_3 * arr_4

array([ 2,  8, 18, 32])

In [81]:
# Divide
arr_3 / arr_4
# Random 4 digit 1D array between 0 to 100
arr_5 = random.randint(100, size=(4))
arr_5

array([23, 21, 52, 13])

In [82]:
# Random 2 by 3 digit 2D array between 0 to 100
arr_6 = random.randint(100, size=(2, 3))
arr_6

array([[97, 22, 37],
       [ 8, 13, 17]])

In [83]:
# 4 random floats
bbb = random.rand(4)
bbb

array([0.68035075, 0.53399807, 0.01519749, 0.91760089])

In [84]:
arr_3

array([1, 2, 3, 4])

In [85]:
# Get random value from an array
random.choice(bbb)

0.9176008938255553

In [86]:
# Sum of values in array
arr_3.sum()

10

In [87]:
# Sum columns
print(arr_6)
arr_6.sum(axis=0)

[[97 22 37]
 [ 8 13 17]]


array([105,  35,  54])

In [88]:
# Cumulative sum of rows
arr_6.cumsum(axis=1)

array([[ 97, 119, 156],
       [  8,  21,  38]])

In [89]:
golf_scores=np.random.randint(3,6,size=(5,9))

golf_scores

array([[3, 4, 3, 3, 4, 5, 5, 5, 4],
       [5, 4, 5, 5, 4, 5, 3, 5, 4],
       [3, 4, 3, 3, 3, 4, 3, 5, 5],
       [3, 3, 3, 3, 4, 3, 4, 3, 4],
       [3, 3, 5, 4, 4, 3, 4, 5, 4]])

In [90]:
golf_scores.cumsum(axis=1)

array([[ 3,  7, 10, 13, 17, 22, 27, 32, 36],
       [ 5,  9, 14, 19, 23, 28, 31, 36, 40],
       [ 3,  7, 10, 13, 16, 20, 23, 28, 33],
       [ 3,  6,  9, 12, 16, 19, 23, 26, 30],
       [ 3,  6, 11, 15, 19, 22, 26, 31, 35]])

In [91]:
golf_scores.sum(axis=1)

array([36, 40, 33, 30, 35])

In [92]:
# Min of each row
arr_6.min(axis=1)
# Max of each column
arr_6.max(axis=0)

print("arr_3", arr_3)
print("arr_4", arr_4)

arr_3 [1 2 3 4]
arr_4 [2 4 6 8]


In [93]:
# Add individual numbers to array
np.add(arr_3, 5)

array([6, 7, 8, 9])

In [94]:
# Add arrays
np.add(arr_3, arr_4)

array([ 3,  6,  9, 12])

In [95]:
# Subtract
np.subtract(arr_3, arr_4)
# Multiply
np.multiply(arr_3, arr_4)
# Divide
np.divide(arr_3, arr_4)

arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
print("arr_5\n", arr_5)
print("arr_6\n", arr_6)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]


In [96]:
# Divides elements in 1st array by 2nd array and returns remainder
np.remainder(arr_6, arr_5)

array([[0, 0],
       [0, 1]])

In [97]:
# Return values in 1st array to powers defined in 2nd array
np.power(arr_6, arr_5)

array([[   2,   16],
       [ 216, 6561]])

In [98]:
# Square root
np.sqrt(arr_3)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [99]:
# Cube root
np.cbrt(arr_3)

array([1.        , 1.25992105, 1.44224957, 1.58740105])

In [100]:
# Absolute value of every element
np.absolute([-1, -2])

array([1, 2])

In [101]:
np.absolute(arr_3)

array([1, 2, 3, 4])

In [102]:
ar1 = arr_3 * -3
ar1

array([ -3,  -6,  -9, -12])

In [103]:
np.absolute(ar1)

array([ 3,  6,  9, 12])

In [104]:
# Exponential of all elements in array
np.exp(arr_3)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [105]:
# log functions
np.log(arr_3)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [106]:
np.log2(arr_3)
np.log10(arr_3)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [107]:
# Greatest common divisor
np.gcd.reduce([9, 12, 15])

3

In [108]:
# Lowest common multiple
np.lcm.reduce([9, 12, 15])

180

In [109]:
# Round down
np.floor([1.2, 2.5])

array([1., 2.])

In [110]:
# Round up
np.ceil([1.2, 2.5])

array([2., 3.])

In [111]:
# Can receive 6 values and square them
sq_arr = np.arange(6)**2
sq_arr

array([ 0,  1,  4,  9, 16, 25])

In [112]:
sq_arr[arr_3]

array([ 1,  4,  9, 16])

In [113]:
arr_7 = random.randint(100, size=(5, 3))
print("arr_7\n", arr_7)

arr_7
 [[30 71 11]
 [49 61 68]
 [72  5 17]
 [70 69 22]
 [69 46 59]]


In [114]:
# Get index for max value per column
mc_index = arr_7.argmax(axis=0)
mc_index

array([2, 0, 1])

In [115]:
# Get numbers corresponding to indexes
max_nums = arr_7[mc_index]
arr_7[mc_index, range(arr_7.shape[1])]

array([72, 71, 68])

### Reading from Files

In [116]:
#! wget https://raw.githubusercontent.com/derekbanas/NumPy-Tutorial/master/icecreamsales.csv
! cat icecreamsales.csv













40,320

In [117]:
# Pandas is used to manipulate tabular data and more
import pandas as pd
# Import using NumPy
from numpy import genfromtxt

# Read table of data from CSV file and convert to Numpy array
ic_sales = pd.read_csv('icecreamsales.csv').to_numpy()
ic_sales

array([[ 37, 292],
       [ 40, 228],
       [ 49, 324],
       [ 61, 376],
       [ 72, 440],
       [ 79, 496],
       [ 83, 536],
       [ 81, 556],
       [ 75, 496],
       [ 64, 412],
       [ 53, 324],
       [ 40, 320]])

In [118]:
# Read data using NumPy
ic_sales_2 = genfromtxt('icecreamsales.csv', delimiter=',')
ic_sales_2

array([[ nan,  nan],
       [ 37., 292.],
       [ 40., 228.],
       [ 49., 324.],
       [ 61., 376.],
       [ 72., 440.],
       [ 79., 496.],
       [ 83., 536.],
       [ 81., 556.],
       [ 75., 496.],
       [ 64., 412.],
       [ 53., 324.],
       [ 40., 320.]])

In [119]:
print(type(ic_sales_2))

<class 'numpy.ndarray'>


In [120]:
# Remove any row with all NANs
ic_sales_2 = [row[~np.isnan(row)] for row in ic_sales_2]
ic_sales_2

[array([], dtype=float64),
 array([ 37., 292.]),
 array([ 40., 228.]),
 array([ 49., 324.]),
 array([ 61., 376.]),
 array([ 72., 440.]),
 array([ 79., 496.]),
 array([ 83., 536.]),
 array([ 81., 556.]),
 array([ 75., 496.]),
 array([ 64., 412.]),
 array([ 53., 324.]),
 array([ 40., 320.])]

### Statistics Functions

In [121]:
# Array 1 - 5
sarr_1 = np.arange(1, 6)
np.mean(sarr_1)

3.0

In [122]:
np.median(sarr_1)

3.0

In [123]:
np.average(sarr_1)

3.0

In [124]:
np.std([4, 6, 3, 5, 2]) # Standard Deviation

1.4142135623730951

In [125]:
np.var([4, 6, 3, 5, 2]) # Variance

2.0

In [126]:
# Also nanmedian, nanmean, nanstd, nanvar

print("ic_sales\n", ic_sales)
# Get the 50th percentile of the data
np.percentile(ic_sales, 50, axis=0)

ic_sales
 [[ 37 292]
 [ 40 228]
 [ 49 324]
 [ 61 376]
 [ 72 440]
 [ 79 496]
 [ 83 536]
 [ 81 556]
 [ 75 496]
 [ 64 412]
 [ 53 324]
 [ 40 320]]


array([ 62.5, 394. ])

In [127]:
np.percentile(ic_sales, 90, axis=0)

array([ 80.8, 532. ])

In [128]:
# Get 1st column
ic_sales[:,0]

array([37, 40, 49, 61, 72, 79, 83, 81, 75, 64, 53, 40])

In [129]:
ic_sales[:,1] #2nd column

array([292, 228, 324, 376, 440, 496, 536, 556, 496, 412, 324, 320])

In [130]:
try: # third column except there is no 3rd column
    ic_sales[:,2]
except:
    print('duh')

duh


In [131]:
# Correlation coefficient : Measure of correlation between data
# Closer to 1 the more the data is correlated
'''
Numpy implements a corrcoef() 
function that returns a matrix of 
correlations of x with x, x with y, y with x and y with y. 

'''
np.corrcoef(ic_sales[:,0], ic_sales[:,1])

array([[1.        , 0.96181329],
       [0.96181329, 1.        ]])

In [132]:
# chaos monkey add some random values of 2
ic_sales[0,0] = 2

ic_sales[2,0] = 2

ic_sales


array([[  2, 292],
       [ 40, 228],
       [  2, 324],
       [ 61, 376],
       [ 72, 440],
       [ 79, 496],
       [ 83, 536],
       [ 81, 556],
       [ 75, 496],
       [ 64, 412],
       [ 53, 324],
       [ 40, 320]])

In [133]:
# not as highly correlated
np.corrcoef(ic_sales[:,0], ic_sales[:,1])

array([[1.        , 0.79871127],
       [0.79871127, 1.        ]])

In [134]:
# Calculating Regression line
# Σ(x-x̅)*(y-ȳ) / Σ(x-x̅)2
temp_mean = np.mean(ic_sales[:,0])
sales_mean = np.mean(ic_sales[:,1])
numerator = np.sum(((ic_sales[:,0] - temp_mean)*(ic_sales[:,1] - sales_mean)))
denominator = np.sum(np.square(ic_sales[:,0] - temp_mean))
slope = numerator/denominator
# Calculate y intercept
y_i = sales_mean - slope * temp_mean
y_i
reg_arr = ic_sales[:,0] * slope + y_i
reg_arr

array([244.82107311, 357.49876525, 244.82107311, 419.76801616,
       452.38524283, 473.14165981, 485.00246951, 479.07206466,
       461.28085011, 428.66362344, 396.04639677, 357.49876525])

### Trig Functions

In [135]:
# Generate array of 200 values between -pi & pi
t_arr = np.linspace(-np.pi, np.pi, 200)

# Plot with x axis & y axis data 
# plt.plot(t_arr, np.sin(t_arr)) # SIN
# plt.plot(t_arr, np.cos(t_arr)) # COS
# plt.plot(t_arr, np.tan(t_arr)) # TAN
# Display plot
# plt.show()

# Provides inverse of If y = cos(x), x = arccos(y)
np.arcsin(1)
np.arccos(1)
np.arctan(0)

# Also arctan2, sinh, cosh, tanh, arcsinh, arccosh, arctanh

# Radians to degrees
np.rad2deg(np.pi)
# Degrees to radians
np.deg2rad(180)

# Hypotenuse c = √w² + h²
np.hypot(10,10)

14.142135623730951

### Matrix Functions

In [136]:
from numpy import linalg as LA

print("arr_5\n", arr_5)
print("arr_6\n", arr_6)
arr_8 = np.array([[5, 6], [7, 8]])

# Matrix multiplication with Dot Product
# (1 * 2) + (2 * 6) = 14 [0,0]
# (1 * 4) + (2 * 9) = 22 [0,1]
# (3 * 2) + (4 * 6) = 30 [1,0]
# (3 * 4) + (4 * 9) = 12 + 36 = 48 [1,1]
np.dot(arr_5, arr_6)
# Compute dot product of 2 or more arrays
LA.multi_dot([arr_5, arr_6, arr_8])

# Inner product 
# (1 * 2) + (2 * 4) = 10 [0,0]
# (1 * 6) + (2 * 9) = 24 [0,1]
# (3 * 2) + (4 * 4) = 22 [1,0]
# (3 * 6) + (4 * 9) = 54 [1,1]
np.inner(arr_5, arr_6)
np.dot(arr_5, arr_6)

# Tensor Dot Product
# (1 * 1) + (2 * 2) + (3 * 3) + (4 * 4) = 30
# (5 * 1) + (6 * 2) + (7 * 3) + (8 * 4) = 
arr_9 = np.array([[[1, 2],
        [3, 4]],
       [[5, 6],
        [7, 8]]])
arr_10 = np.array([[1, 2],
       [3, 4]], dtype=object)
np.tensordot(arr_9, arr_10)

# Einstein Summation : Provides many ways to perform
# operations on multiple arrays
arr_11 = np.array([0, 1])
arr_12 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# Left Side of -> : 1 axis for arr_11 and 2 axis for arr_12
# Right of -> : Array we want (1D Array)
# ij : Means multiply arr_11 single item by each column of arr_12 and sum
# [0, 4 + 5 + 6 + 7]
np.einsum('i,ij->i', arr_11, arr_12)
# Sum values in arr_11
np.einsum('i->', arr_11)
# Dot Product
print("arr_3\n", arr_3)
print("arr_4\n", arr_4)
np.einsum('i,i->', arr_3, arr_4)
# Matrix multiplication
np.einsum('ij,jk', arr_5, arr_6)
# Get diagonal
np.einsum('ii', arr_5)
# Transpose
np.einsum('ji', arr_5)

# Raise matrix to the power of n
# Given [[a, b], [c, d]]
# [[a² + bc, ab +db], [ac + dc, d² + bc]
LA.matrix_power(arr_5, 2)

# Kronecker product of 2 arrays
# Given [[a, b], [c, d]], [[e, f], [g, h]]
# [[a*e, a*f, b*e, b*f], [a*g, a*h, b*g, b*h], ...]
np.kron(arr_5, arr_6)

# Compute eigenvalues
LA.eig(arr_5) # Returns eigenvectors
LA.eigvals(arr_5)

# Get Vector Norm sqrt(sum(x**2))
LA.norm(arr_5)

# Get Multiplicative Inverse of a matrix
LA.inv(arr_5)

# Get Condition number of matrix
LA.cond(arr_5)

# Determinates are used to compute volume, area, to solve systems
# of equations and more. It is a way you can multiply values in a
# matrix to get 1 number.
# For a matrix to have an inverse its determinate must not equal 0
# det([[a, b], [c, d]]) = a*d - b*c
arr_12 = np.array([[1, 2], [3, 4]])
# 1*4 - 2*3 = -2
LA.det(arr_12)

# Determinate of 3x3 Matrix
# det([[a, b, c], [d, e, f], [g, h, i]]) = a*e*i - b*d*i + c*d*h
# - a*f*h + b*f*g - c*e*g

# When we multiply a matrix times its inverse we get the identity
# matrix [[1,0],[0,1]] for a 2x2 matrix
# Calculate the inverse 1/(a*d - b*c) * [[d, -b], [-c, a]]
# 1/(4 - 6) = -.5 -> [[-.5*4, -.5*-2], [-.5*-3, -.5*a]]
arr_12_i = LA.inv(arr_12)
arr_12_i

np.dot(arr_12, arr_12_i)

# Solving Systems of Linear Equations
# If you have 3x + 5 = 9x -> 5 = 6x -> x = 5/6
# If you have x + 4y = 10 & 6x + 18y = 42
# Isolate x -> x = 10 - 4y
# 6(10 - 4y) + 18y = 42 -> 60 - 24y + 18y = 42 - > -6y = -18 -> y = 3
# x + 4*3 = 10 -> x = -2
arr_13 = np.array([[1, 4], [6, 18]])
arr_14 = np.array([10, 42])
# Solve will solve this for you as well
LA.solve(arr_13, arr_14)

# Return a identity matrix with defined number of rows and columns
np.eye(2, 2, dtype=int)

arr_5
 [[1 2]
 [3 4]]
arr_6
 [[2 4]
 [6 9]]
arr_3
 [1 2 3 4]
arr_4
 [2 4 6 8]


array([[1, 0],
       [0, 1]])

### Saving & Loading NumPy Objects

In [137]:
arr_15 = np.array([[1, 2], [3, 4]])
# Save as randarray.npy
np.save('randarray', arr_15)
# Load saved array 
arr_16 = np.load('randarray.npy')
arr_16

# Save as a CSV 
np.savetxt('randcsv.csv', arr_15)
# Load CSV
arr_17 = np.loadtxt('randcsv.csv')
arr_17

array([[1., 2.],
       [3., 4.]])

### Financial Functions

In [140]:
#! conda install -y numpy_financial

In [141]:
# Install in Conda terminal with
# conda install pip
# pip install numpy-financial
import numpy_financial as npf

# Compute future value of $400 investment every month
# with an annual rate of 8% after 10 years
npf.fv(.08/12, 10*12, -400, -400)

# Calculate interest portion of payment on a loan of $3,000
# at 9.25% per year compounded monthly
# Period of loan (year)
period = np.arange(1*12) + 1
principle = 3000.00
# Interest Payment
ipmt = npf.ipmt(0.0925/12, period, 1*12, principle)
# Principle Payment
ppmt = npf.ppmt(0.0925/12, period, 1*12, principle)
for payment in period:
    index = payment - 1
    principle = principle + ppmt[index]
    print(f"{payment}   {np.round(ppmt[index], 2)}    {np.round(ipmt[index],2)}    {np.round(principle, 2)}")

# Compute number of payments to pay off $3,000 if you paid
# $150 per month with an interest rate of 9.25%
np.round(npf.nper(0.0925/12, -150, 3000.00), 2)

# Calculate net present value of cash flows of $4,000, $5,000
# $6,000, $7,000 after $15,000 investment with .08 rate per period
npf.npv(0.08, [-15000, 4000, 5000, 6000, 7000]).round(2)

ModuleNotFoundError: No module named 'numpy_financial'

### Comparison Functions

In [142]:
carr_1 = np.array([2, 3])
carr_2 = np.array([3, 2])
# Returns boolean based on whether arr_1 value Comparison arr_2 value
np.greater(carr_1, carr_2)
np.greater_equal(carr_1, carr_2)
np.less(carr_1, carr_2)
np.less_equal(carr_1, carr_2)
np.not_equal(carr_1, carr_2)
np.equal(carr_1, carr_2)

array([False, False])

In [143]:
# Slicing Bonus
import numpy

avg_monthly_precip = numpy.array([0.70, 0.75, 1.85])
avg_monthly_precip

array([0.7 , 0.75, 1.85])

In [144]:
precip_2002_2013 = numpy.array([[1.07, 0.44, 1.5],
                              [0.27, 1.13, 1.72]])
precip_2002_2013

array([[1.07, 0.44, 1.5 ],
       [0.27, 1.13, 1.72]])

In [145]:
#! conda install -y earthpy

In [146]:
# Import necessary packages
import os

import numpy as np
import earthpy as et


In [147]:
# Download .txt with avg monthly precip (inches)
monthly_precip_url = 'https://ndownloader.figshare.com/files/12565616'
et.data.get_data(url=monthly_precip_url)

# Download .csv of precip data for 2002 and 2013 (inches)
precip_2002_2013_url = 'https://ndownloader.figshare.com/files/12707792'
et.data.get_data(url=precip_2002_2013_url)


'/home/ec2-user/earth-analytics/data/earthpy-downloads/monthly-precip-2002-2013.csv'

In [148]:
# Set working directory to earth-analytics
os.chdir(os.path.join(et.io.HOME, 'earth-analytics'))


In [149]:
# Import average monthly precip
fname = os.path.join("data", "earthpy-downloads",
                     "avg-monthly-precip.txt")

avg_monthly_precip = np.loadtxt(fname)

print(avg_monthly_precip)


[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [150]:
# Import monthly precip for 2002 and 2013
fname = os.path.join("data", "earthpy-downloads",
                     "monthly-precip-2002-2013.csv")

precip_2002_2013 = np.loadtxt(fname, delimiter=",")

print(precip_2002_2013)


[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [151]:
avg_monthly_precip.shape

(12,)

In [152]:
avg_monthly_precip

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

In [153]:
avg_monthly_precip[11]

0.84

In [154]:
try:
    nope = avg_monthly_precip[12]
except:
    nope = None
if nope is None:
    print('not defined')
else:
    print(nope)

not defined


In [155]:
try:
    nope = avg_monthly_precip[-1]
except:
    nope = None
if nope is None:
    print('not defined')
else:
    print(nope)

0.84


In [156]:
avg_monthly_precip

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

In [157]:
print(avg_monthly_precip[2:5])

[1.85 2.93 3.05]


In [158]:
precip_2002_2013.shape

(2, 12)

In [159]:
precip_2002_2013

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [160]:
precip_2002_2013[1, 2]

1.72

In [161]:
precip_2002_2013[1, 11]

0.5

In [162]:
precip_2002_2013[-1, -1]

0.5

# [start_row_index:end_row_index, start_column_index:end_column_index]

In [163]:
print(precip_2002_2013[0:1, 0:2])

[[1.07 0.44]]


In [164]:
print(precip_2002_2013[0:2, 0:1])

[[1.07]
 [0.27]]


In [165]:
print(precip_2002_2013[0:2, 0:3])

[[1.07 0.44 1.5 ]
 [0.27 1.13 1.72]]


In [166]:
#all rows - colums 0 and 1
precip_2002_2013[:, 0:2]

array([[1.07, 0.44],
       [0.27, 1.13]])

In [167]:
precip_2002_2013[:, 0:4]

array([[1.07, 0.44, 1.5 , 0.2 ],
       [0.27, 1.13, 1.72, 4.14]])

In [168]:
precip_2002_2013

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [169]:
# Slice 2nd row, 2nd and 3rd columns
print(precip_2002_2013[1:2, 1:3])


[[1.13 1.72]]


In [170]:
# Slice first two rows, first two columns
print(precip_2002_2013[:2, :2])


[[1.07 0.44]
 [0.27 1.13]]


In [171]:
# Select 1st column
print(precip_2002_2013[:, :])


[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [172]:
precip_2002_2013

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [173]:
print(precip_2002_2013)

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52  2.44  0.78  0.02]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]]


In [174]:
print(precip_2002_2013[:, :-3])

[[ 1.07  0.44  1.5   0.2   3.2   1.18  0.09  1.44  1.52]
 [ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16]]


In [175]:
# Select 2nd row of data for 2013
precip_2013 = precip_2002_2013[1]

print(precip_2013.shape)
print(precip_2013)


(12,)
[ 0.27  1.13  1.72  4.14  2.66  0.61  1.03  1.4  18.16  2.24  0.29  0.5 ]


# (12,) - i think this makes more sense as (12) or (,12) -- 

In [176]:
precip_2013

array([ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
        2.24,  0.29,  0.5 ])

In [177]:
precip_2013[:,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [178]:
precip_2013[:,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [179]:
precip_2013[:]

array([ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
        2.24,  0.29,  0.5 ])

In [180]:
precip_2013[0:3]

array([0.27, 1.13, 1.72])

In [181]:
precip_2013[-4:]

array([18.16,  2.24,  0.29,  0.5 ])

In [183]:
precip_2013[-4:-1]

array([18.16,  2.24,  0.29])

In [188]:
precip_2002_2013

array([[ 1.07,  0.44,  1.5 ,  0.2 ,  3.2 ,  1.18,  0.09,  1.44,  1.52,
         2.44,  0.78,  0.02],
       [ 0.27,  1.13,  1.72,  4.14,  2.66,  0.61,  1.03,  1.4 , 18.16,
         2.24,  0.29,  0.5 ]])

In [196]:
# start at -7 for every row and step by 3's
print(precip_2002_2013[:, -7::3])

[[ 1.18  1.52  0.02]
 [ 0.61 18.16  0.5 ]]


In [197]:
print(precip_2002_2013[:, -10::4])

[[1.5  0.09 0.78]
 [1.72 1.03 0.29]]


In [199]:
print(precip_2002_2013[:, 2::4]) # should be the same with 12 elements - step by 4

[[1.5  0.09 0.78]
 [1.72 1.03 0.29]]
